# Machine Learning II – Tag 3
## Moderne Visualisierungstools II
### Interaktive Visualisierung, Dashboards und Visual Storytelling

**Datum:** 05.06.2026
**Studierender:** Bah Amadou Oury
**Ziel:** Analyseergebnisse interaktiv darstellen und adressatengerecht interpretieren.

In [33]:

import pandas as pd
import matplotlib.pyplot as plt
import plotly.express as px
import seaborn as sns
sns.set_theme(style="whitegrid")

In [34]:
df = pd.read_csv("https://raw.githubusercontent.com/selva86/datasets/master/GermanCredit.csv")
df.head()

,status,duration,credit_history,purpose,amount,savings,employment_duration,installment_rate,personal_status_sex,other_debtors,...,property,age,other_installment_plans,housing,number_credits,job,people_liable,telephone,foreign_worker,credit_risk
0,... < 100 DM,6,critical account/other credits existing,domestic appliances,1169,unknown/no savings account,... >= 7 years,4,male : single,none,...,real estate,67,none,own,2,skilled employee/official,1,yes,yes,1
1,0 <= ... < 200 DM,48,existing credits paid back duly till now,domestic appliances,5951,... < 100 DM,1 <= ... < 4 years,2,female : divorced/separated/married,none,...,real estate,22,none,own,1,skilled employee/official,1,no,yes,0
2,no checking account,12,critical account/other credits existing,retraining,2096,... < 100 DM,4 <= ... < 7 years,2,male : single,none,...,real estate,49,none,own,1,unskilled - resident,2,no,yes,1
3,... < 100 DM,42,existing credits paid back duly till now,radio/television,7882,... < 100 DM,4 <= ... < 7 years,2,male : single,guarantor,...,building society savings agreement/life insurance,45,none,for free,1,skilled employee/official,2,no,yes,1
4,... < 100 DM,24,delay in paying off in the past,car (new),4870,... < 100 DM,1 <= ... < 4 years,3,male : single,none,...,unknown/no property,53,none,for free,2,skilled employee/official,2,no,yes,0

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 21 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   status                   1000 non-null   object
 1   duration                 1000 non-null   int64
 2   credit_history           1000 non-null   object
 3   purpose                  1000 non-null   object
 4   amount                   1000 non-null   int64
 5   savings                  1000 non-null   object
 6   employment_duration      1000 non-null   object
 7   installment_rate         1000 non-null   int64
 8   personal_status_sex      1000 non-null   object
 9   other_debtors            1000 non-null   object
 10  present_residence        1000 non-null   int64
 11  property                 1000 non-null   object
 12  age                      1000 non-null   int64
 13  other_installment_plans  1000 non-null   object
 14  housing                  1000 non-null   object
 15  number_credits           1000 non-null   int64
 16  job                      1000 non-null   object
 17  people_liable            1000 non-null   int64
 18  telephone                1000 non-null   object
 19  foreign_worker           1000 non-null   object
 20  credit_risk              1000 non-null   int64
dtypes: int64(8), object(13)
memory usage: 164.2+ KB

In [36]:
df.describe(include="all")

,status,duration,credit_history,purpose,amount,savings,employment_duration,installment_rate,personal_status_sex,other_debtors,...,property,age,other_installment_plans,housing,number_credits,job,people_liable,telephone,foreign_worker,credit_risk
count,1000,1000.000000,1000,1000,1000.000000,1000,1000,1000.000000,1000,1000,...,1000,1000.000000,1000,1000,1000.000000,1000,1000.000000,1000,1000,1000.000000
unique,4,NaN,5,10,NaN,5,5,NaN,4,3,...,4,NaN,3,3,NaN,4,NaN,2,2,NaN
top,no checking account,NaN,existing credits paid back duly till now,domestic appliances,NaN,... < 100 DM,1 <= ... < 4 years,NaN,male : single,none,...,car or other,NaN,none,own,NaN,skilled employee/official,NaN,no,yes,NaN
freq,394,NaN,530,280,NaN,603,339,NaN,548,907,...,332,NaN,814,713,NaN,630,NaN,596,963,NaN
mean,NaN,20.903000,NaN,NaN,3271.258000,NaN,NaN,2.973000,NaN,NaN,...,NaN,35.546000,NaN,NaN,1.407000,NaN,1.155000,NaN,NaN,0.700000
std,NaN,12.058814,NaN,NaN,2822.736876,NaN,NaN,1.118715,NaN,NaN,...,NaN,11.375469,NaN,NaN,0.577654,NaN,0.362086,NaN,NaN,0.458487
min,NaN,4.000000,NaN,NaN,250.000000,NaN,NaN,1.000000,NaN,NaN,...,NaN,19.000000,NaN,NaN,1.000000,NaN,1.000000,NaN,NaN,0.000000
25%,NaN,12.000000,NaN,NaN,1365.500000,NaN,NaN,2.000000,NaN,NaN,...,NaN,27.000000,NaN,NaN,1.000000,NaN,1.000000,NaN,NaN,0.000000
50%,NaN,18.000000,NaN,NaN,2319.500000,NaN,NaN,3.000000,NaN,NaN,...,NaN,33.000000,NaN,NaN,1.000000,NaN,1.000000,NaN,NaN,1.000000
75%,NaN,24.000000,NaN,NaN,3972.250000,NaN,NaN,4.000000,NaN,NaN,...,NaN,42.000000,NaN,NaN,2.000000,NaN,1.000000,NaN,NaN,1.000000
max,NaN,72.000000,NaN,NaN,18424.000000,NaN,NaN,4.000000,NaN,NaN,...,NaN,75.000000,NaN,NaN,4.000000,NaN,2.000000,NaN,NaN,1.000000

## 3. Wann ist ein Dashboard sinnvoll?

Beantworten Sie kurz:

1. Wann genügt eine Tabelle?

Eine Tabelle genügt, wenn wenige Datenpunkte exakt und detailliert verglichen oder nachgeschlagen werden sollen (z. B. konkrete Werte, Listen, kleine Datensätze).

2. Wann genügt ein einzelnes Diagramm?

Ein einzelnes Diagramm reicht, wenn nur eine zentrale Kennzahl oder ein klarer Zusammenhang visualisiert werden soll (z. B. Trend, Verteilung oder Vergleich einer Variable

3. Wann wird ein Dashboard notwendig?

Ein Dashboard wird notwendig, wenn mehrere Kennzahlen gleichzeitig überwacht und kombiniert dargestellt werden müssen, besonders bei komplexen Daten oder Entscheidungsprozessen in Echtzeit oder regelmäßigem Monitoring.

4. Welche Zielgruppe würde ein Dashboard nutzen?

Dashboards werden vor allem von Entscheidungsträgern und Anwendern mit Analysebedarf genutzt, z. B. Manager, Analysten, Projektleiter oder Fachabteilungen.

### Meine Antwort

Eine Tabelle genügt, wenn Einzelwerte geprüft werden sollen.
Ein Diagramm genügt, wenn eine einzelne Verteilung oder ein Zusammenhang gezeigt werden soll.
Ein Dashboard ist sinnvoll, wenn mehrere Kennzahlen und Diagramme gemeinsam eine Entscheidung unterstützen sollen.

## 4. Interaktives Histogramm mit Plotly

In [37]:
import plotly.express as px

fig=px.histogram(df, x="age", color="credit_risk")

fig.show()

### Interpretation

Das Histogramm zeigt die GermanCredit.
Durch die farbliche Trennung nach `credit_risk` kann geprüft werden, ob bestimmte Altersgruppen häufiger überlebt haben.
Die Interaktivität hilft, einzelne Bereiche genauer zu betrachten.

## 5. Interaktiver Scatterplot

In [38]:

import plotly.express as px

fig = px.scatter(
    df,
    x="age",
    y="amount",
    color="credit_risk",
    hover_data=["status", "purpose", "job"],
    title="Alter vs. Kreditbetrag",
    labels={"age": "Alter", "credit_risk": "Kreditrisiko"}
)

fig.show()

In [39]:

df["credit_risk"].value_counts()

credit_risk
1    700
0    300
Name: count, dtype: int64

## 6. Plotly bewerten

Beantworten Sie:

1. Welche zusätzlichen Informationen liefert die Hover-Funktion?

2. Welche Muster sind besser erkennbar?

3. Welche Zielgruppe profitiert von dieser Darstellung?

## 7. Zielvariable als interaktives Balkendiagramm

In [40]:
import plotly.express as px

credit_risk_counts = df["credit_risk"].value_counts().reset_index()
credit_risk_counts.columns = ["credit_risk", "Anzahl"]

fig = px.bar(
  credit_risk_counts,
    x="credit_risk",
    y="Anzahl",
    text="Anzahl",
    title="Verteilung der Zielvariable credit_risk",
    labels={
        "credit_risk": "Kreditrisiko",
        "Anzahl": "Anzahl der Kunden"
    }
)

fig.show()

### Interpretation

Die Zielvariable ist nicht vollständig ausgeglichen.
Mehr Personen haben nicht überlebt als überlebt.
Für ein späteres Klassifikationsmodell bedeutet das, dass Accuracy allein nicht ausreichen könnte.

## 8. KPI berechnen

In [41]:
anzahl_kunden = len(df)

kredit_risiko_rate = df["credit_risk"].mean()
durchschnittsalter = df["age"].mean()
durchschnitt_kreditbetrag = df["amount"].mean()

print("Anzahl Kunden:", anzahl_kunden)
print("Kreditrisiko-Rate:", round(kredit_risiko_rate * 100, 2), "%")
print("Durchschnittsalter:", round(durchschnittsalter, 2))
print("Durchschnittlicher Kreditbetrag:", round(durchschnitt_kreditbetrag, 2))

Anzahl Kunden: 1000
Kreditrisiko-Rate: 70.0 %
Durchschnittsalter: 35.55
Durchschnittlicher Kreditbetrag: 3271.26

## 9. KPI-Karte mit Plotly

In [42]:
import plotly.graph_objects as go

kredit_rate = df["credit_risk"].mean() * 100

fig = go.Figure()

fig.add_trace(go.Indicator(
    mode="number",
    value=kredit_rate,
    title={"text": "Anteil credit_risk = 1 in %"},
    number={"suffix": "%", "valueformat": ".2f"}
))

fig.update_layout(
    title="KPI: Kreditqualität (German Credit)",
    height=300
)

fig.show()

### Interpretation KPI

Die KPI verdichtet die Zielvariable auf einen zentralen Wert.
Sie eignet sich für ein Dashboard, weil sie schnell einen Überblick gibt.
Allein reicht sie aber nicht aus, da Ursachen und Gruppenunterschiede noch nicht sichtbar sind.

## 10. Dashboard-Elemente vorbereiten

In [44]:

import plotly.express as px
fig1 = px.histogram(
    df,
    x="age",
    color="credit_risk",
    title="Altersverteilung nach Kreditrisiko"
)

fig2 = px.box(
    df,
    x="credit_risk",
    y="amount",
    title="Kreditbetrag nach Kreditrisiko"
)

fig3 = px.bar(
    df.groupby("job", observed=True)["credit_risk"]
      .mean()
      .reset_index(),
    x="job",
    y="credit_risk",
    title="Kreditrisiko nach Beruf",
    labels={
        "credit_risk": "Durchschnittliches Kreditrisiko",
        "job": "Beruf"
    }
)

fig1.show()
fig2.show()
fig3.show()
#Chaque colonne = une feature

## 11. Übung 4 – Dashboard analysieren

Bewerten Sie die drei Visualisierungen:

1. Welche KPI oder Aussage steht im Mittelpunkt?
2. Welche Visualisierung ist am wichtigsten?
3. Welche Entscheidung könnte daraus folgen?
4. Was fehlt noch für ein gutes Dashboard?

## 12. Visual Storytelling

Formulieren Sie eine Datenstory nach dem Schema:

1. Problem

Wir möchten verstehen, welche Faktoren mit einem erhöhten oder niedrigeren Kreditrisiko zusammenhängen.

2. Analyse

Alter, Kreditbetrag, Beruf, Kontostatus und Verwendungszweck wurden visuell untersucht.

3. Erkenntnis

Das Kreditrisiko unterscheidet sich je nach Kundengruppe und Kreditmerkmalen. Besonders Kreditbetrag, Alter und berufliche Situation können Hinweise auf unterschiedliche Risikoprofile geben.

4. Handlungsempfehlung

Für ein späteres ML-Modell sollten Merkmale wie amount, age, duration, job, credit_history, savings und purpose berücksichtigt werden.

## 14. FPA / ILP – Eigenes Dashboard oder Analysebericht

Erstellen Sie nun ein eigenes Dashboard oder einen Analysebericht.

**Pflichtbestandteile:**

1. Projektdatensatz
2. kurze Ausgangssituation
3. mindestens drei Visualisierungen
4. mindestens eine KPI
5. eine zentrale Erkenntnis
6. eine Handlungsempfehlung
7. Reflexion zum Nutzen für spätere ML-Schritte

## 15. Abschlussreflexion

Ergänzen Sie:

**Meine wichtigste Visualisierung ist:**
...

**Die wichtigste Erkenntnis ist:**
...

**Eine mögliche Handlungsempfehlung lautet:**
...

**Für ein späteres ML-Modell bedeutet das:**
...

**Mein nächster Schritt wäre:**
...

## 16. Kurzpräsentation

Bereiten Sie eine 3-Minuten-Präsentation vor:

1. Welcher Datensatz?
2. Welche wichtigste Visualisierung?
3. Welche Erkenntnis?
4. Welche Handlungsempfehlung?